"use client";

import React from "react";
import {
  MdHome,
  MdWork,
  MdSettings,
  MdSecurity,
  MdPeople,
  MdLocationOn,
  MdBadge,
  MdAccessTime,
  MdCalendarMonth,
  MdChat,
  MdBeachAccess,
  MdSchedule,
  MdTimer,
  MdPayments,
  MdSwapHoriz,
  MdAlarmOn,
  MdCardGiftcard,
  MdBusiness,
  MdPolicy,
  MdAdminPanelSettings,
  MdLocalShipping,
  MdStorefront,
  MdCategory,
  MdInventory,
  MdCheckroom,
  MdAssignmentReturn,
  MdAssessment,
  MdInfo,
  MdCampaign,
  MdNotificationsActive,
  MdAssignment,
  MdPlaylistAddCheck,
  MdFormatListBulleted,
  MdAddCircleOutline,
  MdPendingActions,
  MdCalendarToday,
  MdSupervisorAccount,
} from "react-icons/md";

const menuItems = () => {
  return [
    {
      title: "Dashboard Home",
      path: "/dashboard/home",
      key: "home",
      description: "Main HR management overview, metrics, and quick actions",
      icon: <MdHome className="text-lg" />,
    },
    {
      title: "Employee Chat",
      path: "/dashboard/chat",
      key: "chat",
      description: "Message any colleague in real time, see who's online",
      icon: <MdChat className="text-lg" />,
    },
    {
      title: "Command Center & Governance",
      path: "/dashboard/accountability",
      key: "accountability-management",
      icon: <MdSecurity className="text-lg text-brand-gold" />,
      children: [
        {
          title: "Command Center",
          path: "/dashboard/accountability",
          key: "command-center",
          description: "Enterprise command center, attention queue, and governance overview",
          icon: <MdAssessment className="text-base" />,
        },
        {
          title: "Attention Queue",
          path: "/dashboard/accountability/attention",
          key: "attention-queue",
          description: "Prioritized critical, overdue, due soon, and waiting approval directives",
          icon: <MdPendingActions className="text-base" />,
        },
        {
          title: "My Responsibilities",
          path: "/dashboard/accountability/my-obligations",
          key: "my-obligations",
          description: "Personal obligations combining unread notices and active assigned tasks",
          icon: <MdPlaylistAddCheck className="text-base" />,
        },
        {
          title: "Activity Stream",
          path: "/dashboard/accountability/activity",
          key: "activity-stream",
          description: "Live append-only audit feed of all management instructions and staff actions",
          icon: <MdCampaign className="text-base" />,
        },
        {
          title: "Directive Search",
          path: "/dashboard/accountability/search",
          key: "accountability-search",
          description: "Global search across notices, directives, tasks, and employees",
          icon: <MdAssignment className="text-base" />,
        },
        {
          title: "Governance Reports",
          path: "/dashboard/accountability/reports",
          key: "accountability-reports",
          description: "Source-wise, employee workload, and deadline compliance reports",
          icon: <MdAssessment className="text-base" />,
        },
      ],
    },
    {
      title: "Notice & Announcements",
      path: "/dashboard/notices",
      key: "notice-management",
      icon: <MdCampaign className="text-lg" />,
      children: [
        {
          title: "My Notices",
          path: "/dashboard/notices/my-notices",
          key: "my-notices",
          description: "Official announcements, management instructions, and notices requiring your acknowledgement",
          icon: <MdNotificationsActive className="text-base" />,
        },
        {
          title: "Notice Center & Audit",
          path: "/dashboard/notices",
          key: "notices",
          description: "Publish notices, monitor employee views, acknowledgements, and audit logs",
          icon: <MdCampaign className="text-base" />,
        },
      ],
    },
    {
      title: "Task & Instructions",
      path: "/dashboard/tasks",
      key: "task-management",
      icon: <MdAssignment className="text-lg" />,
      children: [
        {
          title: "My Tasks",
          path: "/dashboard/tasks/my-tasks",
          key: "my-tasks",
          description: "Personal tasks, progress updates, proof submission, and deadline tracking",
          icon: <MdPlaylistAddCheck className="text-base" />,
        },
        {
          title: "Task Directory",
          path: "/dashboard/tasks",
          key: "tasks",
          description: "Master list of instructions from MD Sir, Director, Management, and HR",
          icon: <MdFormatListBulleted className="text-base" />,
        },
        {
          title: "New Instruction",
          path: "/dashboard/tasks/create",
          key: "task-create",
          description: "Issue new management instructions and assign to staff or branches",
          icon: <MdAddCircleOutline className="text-base" />,
          hiddenInSidebar: true,
        },
        {
          title: "Executive Dashboard",
          path: "/dashboard/tasks/dashboard",
          key: "task-dashboard",
          description: "KPI summary, source-wise instructions, priority matrix, and recent activity",
          icon: <MdAssessment className="text-base" />,
        },
        {
          title: "Follow-Up & Overdue",
          path: "/dashboard/tasks/follow-up",
          key: "task-followup",
          description: "Priority follow-up queue: overdue, due today, and awaiting approval",
          icon: <MdPendingActions className="text-base" />,
        },
        {
          title: "Task Calendar",
          path: "/dashboard/tasks/calendar",
          key: "task-calendar",
          description: "Visual calendar view of start dates, deadlines, and milestone schedules",
          icon: <MdCalendarToday className="text-base" />,
        },
        {
          title: "Task Reports & Export",
          path: "/dashboard/tasks/reports",
          key: "task-reports",
          description: "Source-wise, branch-wise, and employee workload reports with Excel/PDF export",
          icon: <MdAssessment className="text-base" />,
        },
        {
          title: "Task Categories",
          path: "/dashboard/tasks/categories",
          key: "task-categories",
          description: "Manage task categories and classification tags",
          icon: <MdCategory className="text-base" />,
        },
      ],
    },
    {
      title: "Employee Management",
      path: "/dashboard/employee",
      key: "employee-management",
      icon: <MdPeople className="text-lg" />,
      children: [
        {
          title: "Employee Directory",
          path: "/dashboard/employee",
          key: "employee",
          description: "View, create, update, and manage employee profiles and credentials",
          icon: <MdPeople className="text-base" />,
        },
        {
          title: "Employee Duty Time",
          path: "/dashboard/employee/duty-time",
          key: "employee-duty-time",
          description: "Configure and assign shifts and work schedules to employees",
          icon: <MdAccessTime className="text-base" />,
        },
      ],
    },
    {
      title: "Asset Management",
      path: "/dashboard/assets",
      key: "asset-management",
      icon: <MdCheckroom className="text-lg" />,
      children: [
        {
          title: "Asset Directory",
          path: "/dashboard/assets",
          key: "assets",
          description: "Track every uniform, key, and company asset issued to staff",
          icon: <MdInventory className="text-base" />,
        },
        {
          title: "Asset Types",
          path: "/dashboard/assets/types",
          key: "asset-types",
          description: "Manage the master list of asset & uniform types",
          icon: <MdCategory className="text-base" />,
        },
        {
          title: "My Assets",
          path: "/dashboard/assets/my-assets",
          key: "my-assets",
          description: "View and manage company assets and uniforms issued to you",
          icon: <MdBadge className="text-base" />,
        },
        {
          title: "Employee Asset Report",
          path: "/dashboard/assets/employee-report",
          key: "employee-asset-report",
          description: "Audit & report all company assets and uniforms issued to employees",
          icon: <MdAssessment className="text-base" />,
        },
        {
          title: "Exit Clearance",
          path: "/dashboard/assets/clearance",
          key: "asset-clearance",
          description: "Pending asset returns for resigned or terminated employees",
          icon: <MdAssignmentReturn className="text-base" />,
        },
      ],
    },
    {
      title: "Vendor Management",
      path: "/dashboard/vendors",
      key: "vendor-management",
      icon: <MdLocalShipping className="text-lg" />,
      children: [
        {
          title: "Vendor Directory",
          path: "/dashboard/vendors",
          key: "vendors",
          description: "A-to-Z record of every vendor: contacts, purchases, warranties, and service history",
          icon: <MdStorefront className="text-base" />,
        },
        {
          title: "Vendor Details",
          path: "/dashboard/vendors/[id]",
          key: "vendor-details",
          description: "Specific vendor profile, purchases, warranties, contracts, and service history",
          icon: <MdInfo className="text-base" />,
          hiddenInSidebar: true,
        },
        {
          title: "Vendor Report",
          path: "/dashboard/vendors/report",
          key: "vendor-report",
          description: "Executive audit & summary report of vendors, purchases, and contract status",
          icon: <MdAssessment className="text-base" />,
        },
        {
          title: "Vendor Categories",
          path: "/dashboard/vendors/categories",
          key: "vendor-categories",
          description: "Manage vendor category types (ISP, CCTV, AC, IT, Security, etc.)",
          icon: <MdCategory className="text-base" />,
        },
        {
          title: "Product Categories",
          path: "/dashboard/vendors/product-categories",
          key: "product-categories",
          description: "Manage product & item category types for purchases and inventory",
          icon: <MdCategory className="text-base" />,
        },
      ],
    },
    {
      title: "Organization Setup",
      path: "/dashboard/settings",
      key: "org-setup",
      icon: <MdBusiness className="text-lg" />,
      children: [
        {
          title: "Site & General Settings",
          path: "/dashboard/settings",
          key: "settings",
          description: "Manage company info, time zone, print header/footer margins, and HR policies",
          icon: <MdSettings className="text-base" />,
        },
        {
          title: "Gym Calendar",
          path: "/dashboard/calendar",
          key: "calendar",
          description: "Manage gym calendar, holidays, operating schedules, and payroll calculation metadata",
          icon: <MdCalendarMonth className="text-base" />,
        },
        {
          title: "Branch Configuration",
          path: "/dashboard/settings/branches",
          key: "branches",
          description: "Manage gym location branches, contact details, display order, and status",
          icon: <MdLocationOn className="text-base" />,
        },
        {
          title: "Department Configuration",
          path: "/dashboard/settings/departments",
          key: "departments",
          description: "Manage organizational departments, display order, and status",
          icon: <MdWork className="text-base" />,
        },
        {
          title: "Job Position Configuration",
          path: "/dashboard/settings/job-positions",
          key: "job-positions",
          description: "Manage job titles, department assignments, hierarchy order, and active access",
          icon: <MdBadge className="text-base" />,
        },
        {
          title: "Management Persons",
          path: "/dashboard/settings/management-persons",
          key: "management-persons",
          description: "Configure executive management authorities (MD Sir, Director Sir, etc.) and assign employees",
          icon: <MdSupervisorAccount className="text-base" />,
        },
      ],
    },
    {
      title: "Work & Schedules",
      path: "/dashboard/settings/shifts",
      key: "work-schedules-setup",
      icon: <MdSchedule className="text-lg" />,
      children: [
        {
          title: "Shift Configuration",
          path: "/dashboard/settings/shifts",
          key: "shifts",
          description: "Manage work shift schedules, display order, and active status",
          icon: <MdAccessTime className="text-base" />,
        },
        {
          title: "Work Schedule List",
          path: "/dashboard/settings/work-schedules",
          key: "work-schedules",
          description: "Manage weekly work schedules, daily hours, late tolerance, and half-day rules",
          icon: <MdSchedule className="text-base" />,
        },
        {
          title: "Employee Leave Types",
          path: "/dashboard/settings/leave-types",
          key: "leave-types",
          description: "Manage leave categories, paid/unpaid status, carry-forward, and gender rules",
          icon: <MdBeachAccess className="text-base" />,
        },
        {
          title: "Proxy Duty Management",
          path: "/dashboard/settings/proxy-duty",
          key: "proxy-duty",
          description: "Log and track substitute duty swaps, duty dates, and proxy pay allowances",
          icon: <MdSwapHoriz className="text-base" />,
        },
      ],
    },
    {
      title: "Policies & Payroll Setup",
      path: "/dashboard/settings/late-policy",
      key: "policies-setup",
      icon: <MdPolicy className="text-lg" />,
      children: [
        {
          title: "Late & Attendance Policy",
          path: "/dashboard/settings/late-policy",
          key: "late-policy",
          description: "Configure matching methods, grace periods, late tolerances, and deduction rates",
          icon: <MdTimer className="text-base" />,
        },
        {
          title: "Salary Advance Policy",
          path: "/dashboard/settings/advance-policy",
          key: "advance-policy",
          description: "Configure max advance %, max count, deduction methods, and service months",
          icon: <MdPayments className="text-base" />,
        },
        {
          title: "Overtime Policy & Records",
          path: "/dashboard/settings/overtime",
          key: "overtime",
          description: "Manage overtime calculation rate multipliers, max hours, and log overtime records",
          icon: <MdAlarmOn className="text-base" />,
        },
        {
          title: "Bonus Policy Configuration",
          path: "/dashboard/settings/bonus-policy",
          key: "bonus-policy",
          description: "Configure festival, performance, and attendance bonuses and payout months",
          icon: <MdCardGiftcard className="text-base" />,
        },
      ],
    },
    {
      title: "Security & Access",
      path: "/dashboard/settings/roles",
      key: "security-setup",
      icon: <MdAdminPanelSettings className="text-lg" />,
      children: [
        {
          title: "User Role Configuration",
          path: "/dashboard/settings/roles",
          key: "roles",
          description: "Create and manage system user roles and hierarchy order",
          icon: <MdSecurity className="text-base" />,
        },
        {
          title: "Role Access Control",
          path: "/dashboard/settings/role-permissions",
          key: "role-permissions",
          description: "Configure module-level view/add/edit/delete access matrix",
          icon: <MdSecurity className="text-base" />,
        },
      ],
    },
  ];
};

export default menuItems;
